requires = ["tox>=4"]
env_list = ["py312", "py313", "flake8", "sphinx"]

[env.py312]
description = "Run unit tests"
deps = [
    "pytest~=8.4",
]
commands = [
    ["pytest", "{posargs:--}"],
]


[env.py313]
description = "Run unit tests"
deps = [
    "pytest~=8.4",
]
commands = [
    ["pytest", "{posargs:--}"],
]


[env.flake8]
deps = [
    "flake8>=7.3.0",
    "flake8-bugbear",
    "flake8-docstrings",
    "flake8-rst-docstrings",
    "flake8-pyproject",
    "flake8-rst-docstrings",
    "flake8-dunder-all",
    "flake8-mutable",
]
commands = [
    ["flake8", "src/agglovar", "{posargs:--}"],
]


[env.sphinx]
deps = [
    "sphinx>=8.2.3",
    "sphinx-autoapi>=3.6.0",
    "sphinx-rtd-theme>=3.0.2",
#    "polars>=1.33.1",
#    "biopython>=1.85",
#    "edlib>=1.3.9.post1",
#    "numpy>=2.3.0",
#    "ply>=3.11",
]
commands = [
    ["make", "-C", "docs", "clean", "html", "{posargs:--}"],
#    ["sphinx-apidoc", "--force", "--module-first", "--separate", "-o", "docs/source/api/", "src/agglovar"],
#    ["sphinx-build", "-n", "-W", "--keep-going", "-b", "html", "docs/source", "docs/build/"],
]
allowlist_externals = ["make"]


[env.testpypi]
deps = [
    "twine>=6.2.0",
]
commands = [
    ["python3", "-m", "twine", "upload", "--skip-existing", "--repository", "testpypi", "dist/*.whl", "dist/*.tar.gz", "{posargs:--}"],
]

[env.pypi]
deps = [
    "twine>=6.2.0",
]
commands = [
    ["python3", "-m", "twine", "upload", "--skip-existing", "--repository", "pypi", "dist/*.whl", "dist/*.tar.gz", "{posargs:--}"],
]
